In [106]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [107]:
df = pd.read_csv("C:\\Users\\aimay\\OneDrive\\Desktop\AI lab\\marks_final.csv")

In [108]:
df.head()

,SNO.,ROLL NUMBER,Q1 (5),Q2 (5),Q3 (5),Q4 (5),Q5 (5),Q6 (5),Q7 (5),Q8 (5),Q9 (5),Q10 (5),Q11 (5),Q12 (5),Top 9 (out of 45),Out of 30
0,1,102003733,AB,AB,AB,AB,AB,AB,3,5,AB,AB,AB,4,12,8.0
1,2,102203002,5,AB,4,4,4,4,4,3,5,5,5,3,40,26.7
2,3,102203003,5,4,4,4,4,5,4,3,4,5,4,2,39,26.0
3,4,102203005,AB,AB,AB,AB,3,5,3,4,4,5,5,AB,29,19.3
4,5,102203007,AB,AB,AB,5,4,3,3,5,3,5,5,3,36,24.0

In [109]:
df.tail()

,SNO.,ROLL NUMBER,Q1 (5),Q2 (5),Q3 (5),Q4 (5),Q5 (5),Q6 (5),Q7 (5),Q8 (5),Q9 (5),Q10 (5),Q11 (5),Q12 (5),Top 9 (out of 45),Out of 30
1048,1049,102383062,5,4,AB,5,3,4,AB,3,4,5,4,5,39,26.0
1049,1050,102383067,5,2,3,4,3,5,2,5,AB,5,5,5,40,26.7
1050,1051,102383071,5,3,5,4,3,3,4,5,4,5,5,5,42,28.0
1051,1052,102383081,5,3,3,AB,4,AB,AB,5,AB,5,5,3,33,22.0
1052,1053,102383083,AB,AB,3,AB,5,AB,4,AB,AB,4,5,3,24,16.0

In [110]:
df.describe()

             SNO.   ROLL NUMBER  Top 9 (out of 45)    Out of 30
count  1053.00000  1.053000e+03        1053.000000  1053.000000
mean    527.00000  1.027862e+08          38.144349    25.430104
std     304.11922  1.848957e+07           7.150877     4.766492
min       1.00000  1.020037e+08           0.000000     0.000000
25%     264.00000  1.022033e+08          37.000000    24.700000
50%     527.00000  1.022035e+08          40.000000    26.700000
75%     790.00000  1.022038e+08          42.000000    28.000000
max    1053.00000  7.022000e+08          45.000000    30.000000

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1053 entries, 0 to 1052
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SNO.               1053 non-null   int64
 1   ROLL NUMBER        1053 non-null   int64
 2   Q1 (5)             1053 non-null   object
 3   Q2 (5)             1053 non-null   object
 4   Q3 (5)             1053 non-null   object
 5   Q4 (5)             1053 non-null   object
 6   Q5 (5)             1053 non-null   object
 7   Q6 (5)             1053 non-null   object
 8   Q7 (5)             1053 non-null   object
 9   Q8 (5)             1053 non-null   object
 10  Q9 (5)             1053 non-null   object
 11  Q10 (5)            1053 non-null   object
 12  Q11 (5)            1053 non-null   object
 13  Q12 (5)            1053 non-null   object
 14  Top 9 (out of 45)  1053 non-null   int64
 15  Out of 30          1053 non-null   float64
dtypes: float64(1), int64(3), object(12)
memory usage: 131.8+ KB

In [112]:
df.dtypes

SNO.                   int64
ROLL NUMBER            int64
Q1 (5)                object
Q2 (5)                object
Q3 (5)                object
Q4 (5)                object
Q5 (5)                object
Q6 (5)                object
Q7 (5)                object
Q8 (5)                object
Q9 (5)                object
Q10 (5)               object
Q11 (5)               object
Q12 (5)               object
Top 9 (out of 45)      int64
Out of 30            float64
dtype: object

In [113]:
df.isnull().sum()

SNO.                 0
ROLL NUMBER          0
Q1 (5)               0
Q2 (5)               0
Q3 (5)               0
Q4 (5)               0
Q5 (5)               0
Q6 (5)               0
Q7 (5)               0
Q8 (5)               0
Q9 (5)               0
Q10 (5)              0
Q11 (5)              0
Q12 (5)              0
Top 9 (out of 45)    0
Out of 30            0
dtype: int64

In [114]:
df.columns

Index(['SNO.', 'ROLL NUMBER', 'Q1 (5)', 'Q2 (5)', 'Q3 (5)', 'Q4 (5)', 'Q5 (5)',
       'Q6 (5)', 'Q7 (5)', 'Q8 (5)', 'Q9 (5)', 'Q10 (5)', 'Q11 (5)', 'Q12 (5)',
       'Top 9 (out of 45)', 'Out of 30'],
      dtype='object')

In [115]:
print(f" rows {df.shape[0]}")
print(f" column {df.shape[1]}")

 rows 1053
 column 16

In [116]:
df = df.drop(["SNO.","ROLL NUMBER"], axis=1)

In [117]:
df.dtypes

Q1 (5)                object
Q2 (5)                object
Q3 (5)                object
Q4 (5)                object
Q5 (5)                object
Q6 (5)                object
Q7 (5)                object
Q8 (5)                object
Q9 (5)                object
Q10 (5)               object
Q11 (5)               object
Q12 (5)               object
Top 9 (out of 45)      int64
Out of 30            float64
dtype: object

In [118]:
data = pd.DataFrame({'Q1 (5)': df['Q1 (5)'].unique()})
data_LE = LabelEncoder()
data_LE.fit(np.ravel(data))

LabelEncoder()

In [119]:
def convertObjToInt(cols):
    for i in cols:
        data = pd.DataFrame({i:df[i].unique()})
        data_LE = LabelEncoder()
        data_LE.fit(np.ravel(data))    
        df[i] = data_LE.transform(df[i])
        
columns = ['Q1 (5)', 'Q2 (5)', 'Q3 (5)', 'Q4 (5)', 'Q5 (5)',
       'Q6 (5)', 'Q7 (5)', 'Q8 (5)', 'Q9 (5)', 'Q10 (5)', 'Q11 (5)', 'Q12 (5)',]
convertObjToInt(columns)

In [120]:
from sklearn.preprocessing import LabelEncoder

def convertObjToInt(df, cols):
    encoders = {}
    for col in cols:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])
        encoders[col] = le  
    return df, encoders
columns = ['Q1 (5)', 'Q2 (5)','Q3 (5)', 'Q4 (5)', 'Q5 (5)',
       'Q6 (5)', 'Q7 (5)', 'Q8 (5)', 'Q9 (5)', 'Q10 (5)', 'Q11 (5)', 'Q12 (5)',]


df, encoders = convertObjToInt(df, columns)

In [121]:
def changeFloatToInt(cols):
    for i in cols:
        df[i] = df[i].astype('int64')

columns = ['Out of 30']
changeFloatToInt(columns)

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1053 entries, 0 to 1052
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Q1 (5)             1053 non-null   int64
 1   Q2 (5)             1053 non-null   int64
 2   Q3 (5)             1053 non-null   int64
 3   Q4 (5)             1053 non-null   int64
 4   Q5 (5)             1053 non-null   int64
 5   Q6 (5)             1053 non-null   int64
 6   Q7 (5)             1053 non-null   int64
 7   Q8 (5)             1053 non-null   int64
 8   Q9 (5)             1053 non-null   int64
 9   Q10 (5)            1053 non-null   int64
 10  Q11 (5)            1053 non-null   int64
 11  Q12 (5)            1053 non-null   int64
 12  Top 9 (out of 45)  1053 non-null   int64
 13  Out of 30          1053 non-null   int64
dtypes: int64(14)
memory usage: 115.3 KB

In [123]:
df.head()

,Q1 (5),Q2 (5),Q3 (5),Q4 (5),Q5 (5),Q6 (5),Q7 (5),Q8 (5),Q9 (5),Q10 (5),Q11 (5),Q12 (5),Top 9 (out of 45),Out of 30
0,6,6,6,6,6,6,3,5,6,6,6,4,12,8
1,5,6,4,4,4,4,4,3,5,5,5,3,40,26
2,5,4,4,4,4,5,4,3,4,5,4,2,39,26
3,6,6,6,6,3,5,3,4,4,5,5,6,29,19
4,6,6,6,5,4,3,3,5,3,5,5,3,36,24

In [124]:
df.tail()

,Q1 (5),Q2 (5),Q3 (5),Q4 (5),Q5 (5),Q6 (5),Q7 (5),Q8 (5),Q9 (5),Q10 (5),Q11 (5),Q12 (5),Top 9 (out of 45),Out of 30
1048,5,4,6,5,3,4,6,3,4,5,4,5,39,26
1049,5,2,3,4,3,5,2,5,6,5,5,5,40,26
1050,5,3,5,4,3,3,4,5,4,5,5,5,42,28
1051,5,3,3,6,4,6,6,5,6,5,5,3,33,22
1052,6,6,3,6,5,6,4,6,6,4,5,3,24,16

In [125]:
df.to_csv('processed_data.csv', index=False, header=True)

In [126]:
df = pd.read_csv('processed_data.csv')
df

,Q1 (5),Q2 (5),Q3 (5),Q4 (5),Q5 (5),Q6 (5),Q7 (5),Q8 (5),Q9 (5),Q10 (5),Q11 (5),Q12 (5),Top 9 (out of 45),Out of 30
0,6,6,6,6,6,6,3,5,6,6,6,4,12,8
1,5,6,4,4,4,4,4,3,5,5,5,3,40,26
2,5,4,4,4,4,5,4,3,4,5,4,2,39,26
3,6,6,6,6,3,5,3,4,4,5,5,6,29,19
4,6,6,6,5,4,3,3,5,3,5,5,3,36,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048,5,4,6,5,3,4,6,3,4,5,4,5,39,26
1049,5,2,3,4,3,5,2,5,6,5,5,5,40,26
1050,5,3,5,4,3,3,4,5,4,5,5,5,42,28
1051,5,3,3,6,4,6,6,5,6,5,5,3,33,22
1052,6,6,3,6,5,6,4,6,6,4,5,3,24,16

In [127]:
import pandas as pd
df = pd.read_csv('processed_data.csv')
df.columns

Index(['Q1 (5)', 'Q2 (5)', 'Q3 (5)', 'Q4 (5)', 'Q5 (5)', 'Q6 (5)', 'Q7 (5)',
       'Q8 (5)', 'Q9 (5)', 'Q10 (5)', 'Q11 (5)', 'Q12 (5)',
       'Top 9 (out of 45)', 'Out of 30'],
      dtype='object')

In [128]:
X = df.drop('Top 9 (out of 45)', axis=1)   
y = df['Top 9 (out of 45)']

In [129]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X,y, test_size=0.2, shuffle=False)

In [130]:
print(train_X.shape, train_y.shape)
print(test_X.shape, test_y.shape)

(842, 13) (842,)
(211, 13) (211,)

In [131]:
from catboost import CatBoostRegressor
from sklearn.metrics import r2_score, mean_squared_error
import pandas as pd
import numpy as np


cat_model = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.05,
    depth=6,
    verbose=0,
    random_state=42
)

In [132]:
cat_model.fit(train_X, train_y)

In [133]:
y_pred = cat_model.predict(test_X)
y_pred

array([3.98232941e+01, 3.98793084e+01, 4.24735866e+01, 3.93421920e+01,
       3.51172216e+01, 3.98530564e+01, 3.93820097e+01, 3.63766547e+01,
       4.25381970e+01, 3.98794730e+01, 3.96784525e+01, 4.11521681e+01,
       3.98813656e+01, 3.36225019e+01, 4.21604811e+01, 4.20140136e+01,
       4.23155286e+01, 3.94399003e+01, 3.96659022e+01, 4.10269268e+01,
       3.95545879e+01, 3.79044078e+01, 4.22003958e+01, 3.91398826e+01,
       4.12353648e+01, 3.96627432e+01, 4.28154547e+01, 4.36753354e+01,
       3.94326354e+01, 4.38382067e+01, 3.66363555e+01, 3.79517716e+01,
       3.96674601e+01, 4.09984094e+01, 4.09946321e+01, 3.82184892e+01,
       4.10043516e+01, 3.67217160e+01, 4.21534454e+01, 3.94140958e+01,
       4.09451811e+01, 3.61573990e+01, 3.59241434e+01, 4.07228185e+01,
       3.65472067e+01, 4.49498840e+01, 4.48825705e+01, 4.10828704e+01,
       1.93134254e+01, 1.58783989e+01, 3.52165952e+01, 8.93477835e-03,
       3.79218324e+01, 2.54832822e+01, 4.16220263e+01, 3.16738345e+01,
       2.24295265e+01, 2.57671927e+01, 2.99127415e+01, 3.50325435e+01,
       4.24226501e+01, 3.76993896e+01, 3.46568904e+01, 4.11681285e+01,
       3.96991142e+01, 3.95231969e+01, 4.26542665e+01, 3.78125221e+01,
       4.49902760e+01, 3.78262600e+01, 3.96333901e+01, 4.19565650e+01,
       4.27969966e+01, 2.49617031e+01, 3.96143254e+01, 3.66996840e+01,
       3.81557656e+01, 4.45953328e+01, 3.38562505e+01, 4.41150613e+01,
       4.23930419e+01, 3.92386090e+01, 3.67180171e+01, 4.22120653e+01,
       3.37943833e+01, 3.97403688e+01, 4.20841113e+01, 3.97859439e+01,
       4.24100082e+01, 4.21438198e+01, 2.40691059e+01, 4.09487105e+01,
       3.66307633e+01, 4.25875500e+01, 4.24240866e+01, 4.40116639e+01,
       4.23601078e+01, 4.10379592e+01, 4.10082378e+01, 3.97847199e+01,
       3.49538928e+01, 3.49991437e+01, 3.95778594e+01, 4.22225059e+01,
       4.08154875e+01, 3.95925301e+01, 3.96900498e+01, 4.09868632e+01,
       3.75451527e+01, 3.95402639e+01, 4.25928457e+01, 4.26527345e+01,
       4.36798420e+01, 4.22334783e+01, 4.24454925e+01, 4.10427076e+01,
       4.21260409e+01, 4.08663397e+01, 4.08803457e+01, 4.17902048e+01,
       3.63744555e+01, 3.81477110e+01, 4.21051426e+01, 4.11763828e+01,
       4.26941187e+01, 3.95527608e+01, 4.40634631e+01, 3.95934216e+01,
       3.95235740e+01, 4.40068322e+01, 3.98100138e+01, 3.91895735e+01,
       4.23857332e+01, 3.64882271e+01, 2.16898956e+01, 4.09798633e+01,
       4.39705096e+01, 3.94096191e+01, 4.23347050e+01, 3.97865264e+01,
       3.33681922e+01, 3.64849943e+01, 4.10579373e+01, 3.70513390e+01,
       3.66608533e+01, 4.09067133e+01, 3.96615172e+01, 3.68064124e+01,
       4.08401997e+01, 3.99370317e+01, 4.09719772e+01, 8.93477835e-03,
       4.23573334e+01, 4.09968456e+01, 3.96385476e+01, 4.11205861e+01,
       3.99381334e+01, 4.25989700e+01, 4.07894336e+01, 4.08304626e+01,
       3.97091216e+01, 4.22864257e+01, 4.25638817e+01, 4.40550930e+01,
       4.09218534e+01, 3.96586068e+01, 4.42219538e+01, 4.07515056e+01,
       3.97225203e+01, 3.82694672e+01, 3.68366297e+01, 4.19523522e+01,
       3.49602552e+01, 4.23933302e+01, 4.09448431e+01, 4.11609647e+01,
       4.21576335e+01, 4.42710503e+01, 3.93022159e+01, 3.93720535e+01,
       2.75169611e+01, 4.44076954e+00, 3.40069522e+01, 3.97715214e+01,
       3.97390525e+01, 3.97320126e+01, 3.98552681e+01, 4.23101106e+01,
       4.09562376e+01, 4.28970047e+01, 3.67290703e+01, 3.04322072e+01,
       4.23416442e+01, 4.22431564e+01, 4.23729976e+01, 4.25494890e+01,
       3.93113545e+01, 4.25649683e+01, 4.39347623e+01, 3.97857092e+01,
       4.09962614e+01, 3.49001156e+01, 4.07820680e+01, 3.82641819e+01,
       4.09726029e+01, 3.95554767e+01, 3.94304864e+01, 3.97866714e+01,
       4.22647157e+01, 3.38149610e+01, 2.43188940e+01])

In [134]:
r2 = r2_score(test_y, y_pred)
accuracy = round(r2 * 100, 2)  
rmse = np.sqrt(mean_squared_error(test_y, y_pred))

print(f"R2 Score: {accuracy} %")
print(f"Prediction Accuracy: {accuracy} %")
print(f"RMSE: {round(rmse)}")

R2 Score: 98.27 %
Prediction Accuracy: 98.27 %
RMSE: 1

In [135]:
import pickle
model_path = "catboost_marks_model.pkl"
with open(model_path, "wb") as file:
    pickle.dump(cat_model, file)

print(f"Model saved successfully at {model_path}")

Model saved successfully at catboost_marks_model.pkl

In [ ]:
with open("catboost_marks_model.pkl", "rb") as file:
    loaded_model = pickle.load(file)
print("Model loaded successfully!")
y_pred_loaded = loaded_model.predict(test_X)

Model loaded successfully!

In [138]:
import pickle

with open("catboost_marks_model.pkl", "rb") as file:
    model = pickle.load(file)

feature_names = model.feature_names_
print("Columns the model was trained on:")
print(feature_names)

Columns the model was trained on:
['Q1 (5)', 'Q2 (5)', 'Q3 (5)', 'Q4 (5)', 'Q5 (5)', 'Q6 (5)', 'Q7 (5)', 'Q8 (5)', 'Q9 (5)', 'Q10 (5)', 'Q11 (5)', 'Q12 (5)', 'Out of 30']

In [139]:
feature_names = train_X.columns.tolist()
print("Columns used for training:")
print(feature_names)

Columns used for training:
['Q1 (5)', 'Q2 (5)', 'Q3 (5)', 'Q4 (5)', 'Q5 (5)', 'Q6 (5)', 'Q7 (5)', 'Q8 (5)', 'Q9 (5)', 'Q10 (5)', 'Q11 (5)', 'Q12 (5)', 'Out of 30']